# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbbb0417df1f140f370430728f24890a9c7f3442b7bf0d3ab1c2df2dc5400e6e6aac8df1d5b55b0c0e883d2a064ca1a4c619df13c4e3e17914268a3b87e96e0b

test:
  secret_key_base: 94f870342498c94964ed8dc092998be420809d64d2fa47cd5fc291a7a68fd8dc2441d7d863666c0a2422f8a2cc9f771309c8422547a9abbe50ac5f061abbf46f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
